ALTER TABLE users 
MODIFY COLUMN full_name VARCHAR(200) NOT NULL,
MODIFY COLUMN current_status ENUM('employed', 'self-employed', 'unemployed') NOT NULL;

ALTER TABLE employers
MODIFY COLUMN company_name VARCHAR(100) NOT NULL,
MODIFY COLUMN revenue FLOAT NOT NULL,
MODIFY COLUMN is_hiring TINYINT(1) NOT NULL;

ALTER TABLE messages
MODIFY COLUMN company_name VARCHAR(100) NOT NULL,
MODIFY COLUMN user_name VARCHAR(200) NOT NULL,
MODIFY COLUMN message TEXT NOT NULL;